<?php
declare(strict_types=1);

function media_store_upload(array $file, int $userId): array
{
    if (($file['error'] ?? UPLOAD_ERR_NO_FILE) !== UPLOAD_ERR_OK) {
        return ['ok' => false, 'message' => 'Upload failed'];
    }

    $max = setting_int('media_max_bytes', (int) app_config('media.max_bytes', 10485760));
    if (($file['size'] ?? 0) <= 0 || $file['size'] > $max) {
        return ['ok' => false, 'message' => 'File size not allowed'];
    }

    $original = basename((string) ($file['name'] ?? 'file'));
    $ext = strtolower(pathinfo($original, PATHINFO_EXTENSION));
    $allowedExt = app_config('media.allowed_extensions', []);
    if (!in_array($ext, $allowedExt, true)) {
        return ['ok' => false, 'message' => 'Extension not allowed'];
    }

    $finfo = new finfo(FILEINFO_MIME_TYPE);
    $mime = $finfo->file($file['tmp_name']) ?: 'application/octet-stream';
    $allowedMime = app_config('media.allowed_mimes', []);
    if (!in_array($mime, $allowedMime, true)) {
        return ['ok' => false, 'message' => 'MIME type not allowed'];
    }

    $stored = bin2hex(random_bytes(16)) . '.' . $ext;
    $dir = (string) app_config('paths.media');
    if (!is_dir($dir)) {
        mkdir($dir, 0750, true);
    }
    $dest = $dir . DIRECTORY_SEPARATOR . $stored;
    if (!move_uploaded_file($file['tmp_name'], $dest)) {
        return ['ok' => false, 'message' => 'Could not store file'];
    }
    @chmod($dest, 0640);

    $sha = hash_file('sha256', $dest) ?: '';
    $stmt = db()->prepare(
        'INSERT INTO media_files (original_name, stored_name, mime_type, extension, size_bytes, sha256, created_by)
         VALUES (?, ?, ?, ?, ?, ?, ?)'
    );
    $stmt->execute([
        substr($original, 0, 255),
        $stored,
        $mime,
        $ext,
        (int) $file['size'],
        $sha,
        $userId,
    ]);

    $id = (int) db()->lastInsertId();
    audit_log('media_uploaded', 'media', $id, ['mime' => $mime, 'size' => (int) $file['size']]);
    return ['ok' => true, 'id' => $id, 'stored_name' => $stored, 'mime' => $mime];
}

function media_path_by_id(int $id): ?array
{
    $stmt = db()->prepare('SELECT * FROM media_files WHERE id = ?');
    $stmt->execute([$id]);
    $row = $stmt->fetch();
    if (!$row) {
        return null;
    }
    $path = rtrim((string) app_config('paths.media'), '/\\') . DIRECTORY_SEPARATOR . $row['stored_name'];
    // Prevent traversal — stored_name is generated by app only
    if (str_contains($row['stored_name'], '..') || str_contains($row['stored_name'], '/') || str_contains($row['stored_name'], '\\')) {
        return null;
    }
    if (!is_file($path)) {
        return null;
    }
    $row['absolute_path'] = $path;
    return $row;
}
